const fs = require("fs");

const ask = [
  'Y',
  'G',
  'Gay',
  'Betul',
  'Diem lu',
  'Gak tau gw',
  'Coba tebak',
  'Enggak kok',
  'Ya, dia gay',
  'Mungkin iya',
  'Tanya owner',
  'Tanya mulu lu',
  'Coba tanya admin',
  'Kau tak di ajak',
  'Aduh le 100% sih',
  'Lu yang kek kontol',
  'Sebaiknya jangan 🗿',
  'Enggak, dia cantik malahan',
  'Enggak, dia ganteng malahan',
  'Kata siapa?, jelas-jelas kek kontol'
];

const sifatlist = [
  'Baik',
  'Jahat',
  'Lucu',
  'Setia',
  'Pelit',
  'Rajin',
  'Sombong',
  'Bijaksana',
  'Pemalu',
  'Pintar',
  'Cengeng',
  'Pemalas',
  'Sensitif',
  'Pemarah',
  'Dermawan',
  'Penyabar',
  'Cemburuan',
  'Pemberani',
  'Rendah Hati',
  'kek kontol',
  'Percaya Diri'
];

const when = [
  '100 tahun lagi',
  'owner jadi femboy',
  'aku diseriusin',
  'rasa ini hilang',
  'kita ketemu lagi',
  'aku merasa cukup',
  'mimpi jadi kenyataan',
  'aku benar-benar bahagia',
  'hidup nggak sesulit ini',
  'ada yang ngajak nikah',
  'aku nggak jadi plan B orang',
  'semuanya jadi lebih mudah',
  'aku bisa membanggakan orang tuaku',
  'aku bisa berhenti capek terus',
  'ada yang bener-bener sayang sama aku',
  'aku bisa tidur tanpa mikir apa-apa',
  'dompetku tebal bukan karena struk',
  'aku nggak salah terus di mata orang',
  'aku dikira ganteng tanpa harus buka filter',
  'bisa rebahan tanpa rasa bersalah',
  'rambut rontok bisa diklaim BPJS',
  'hidup nggak cuma bangun–kerja–capek–ulang lagi'
];

const cekDosa = [
  'Femboy',
  'Jomok',
  'Rasis',
  'Memfitnah',
  'Bilang bot lemah',
  'Main wa dua arah',
  'Menghina admin',
  'Menghina Member',
  'Menghina Owner',
  'Merayu Admin',
  'Menyiksa lalat',
  'Bilang owner hitam',
  'Bilang "p" doang tiap masuk grup',
  'Cabul ke member',
  'Ngemis di grup',
  'Ngeghost pas ditanya',
  'Nyepam stiker 18+',
  'Nyolong status WA orang',
  'Pura-pura nolep',
  'Sok bijak padahal toxic',
  'Toxic terus tiap malam',
  'Mengejek orang tua',
  'AFK pas giliran debat',
  'Kirim VN napas doang',
  'Promosi dagangan tanpa izin',
  'Suka skip pertanyaan penting',
  'Komen seenak jidat',
  'Kepo tapi gak pernah bantu',
  'Ngasih link phising',
  'Ngegas duluan pas disapa',
  'Kirim stiker mantan terus',
  'Curhat terus tapi gak pernah dengerin orang',
  'Ngaku anak jenderal',
  'Meme tak lucu tapi dipaksa ketawa',
  'Suka kirim gambar blur',
  'Berantem sama bot',
  'Pembokep handal',
  'Kalah debat jadi femboy',
  'Ngaku cewek padahal cowok',
  'Jadi silent reader sejati',
  'Ngaku hacker padahal script kiddie',
  'Ngetag semua member tanpa alasan',
  'Typo parah sampe disangka sandi rahasia',
  'Tiba-tiba left grup tanpa pamit',
  'Kirim foto nasi goreng jam 3 pagi',
  'Gak pernah baca pinned pesan',
  'Pernah menghitamkan grup',
  'Kirim voice note sambil kentut',
  'Join cuma buat liat PP member',
  'Mainin perasaan member'
];

const cekKhodam = [
  'Pace',
  'Agus',
  'Mama',
  'Papa',
  'Adek',
  'Sapi',
  'Biawak',
  'Singa',
  'Zebra',
  'Ciput',
  'Nenek',
  'Cacing',
  'Kaori',
  'Walid',
  'Barbie',
  'Ikan Mas',
  'Macan',
  'Tuyul',
  'Elang',
  'Naruto',
  'Pinokio',
  'Ular Piton',
  'Ular Kobra',
  'Harimau',
  'Domba',
  'Kerbau',
  'Ikan Sepat',
  'Ikan Gabus',
  'Ulat bulu',
  'Kosong',
  'Pisang Hijau',
  'Bando kucing',
  'Kepala casan',
  'Kue jeli pak Herman',
  'Kipas Angis',
  'Farhan Kebab',
  'Rossi Becak',
  'Peti Harta',
  'Kapal karam',
  'Pace Yunus',
  'Zebra Merah',
  'Gondoruwo',
  'Trenggiling',
  'Cinderela',
  'Rusdi Boti',
  'Semut Hitam',
  'Naga Merah',
  'Siput Sumatra',
  'Siimut dari jawa',
  'Kucing Rawa',
  'Biawak Sumatera',
  'Biawak Samudra',
  'Karyawan Indomaret',
  'Kuntilanak Lucu',
  'Handuk basah',
  'Suster ngesot',
  'Titid kuda',
  'Torpedo kambing',
  'Serigala',
  'Listrik Kejut',
  'Pocong berkepala 3',
  'Pinguin Alaskar',
  'Lemari kecoa',
  'Hiu sumanji',
  'Sempak Firaun',
  'Sapi terbang',
  'Jerapah Pendek',
  'Janda anak Pitu',
  'Serigala Jawa',
  'Singa dangdut',
  'Macan kembang',
  'Macan hideng',
  'Macan Ireng',
  'Nyamuk racing',
  'Minyak resing',
  'Api Hermansyah',
  'Serigala berbulu janda'
];

const cekKuat = [
  'Membaca pikiran orang lain',
  'Mengendalikan pikiran',
  'Mengendalikan api',
  'Mengendalikan listrik',
  'Mengendalikan cuaca',
  'Mengendalikan bayangan',
  'Mengendalikan darah',
  'Mengendalikan mimpi orang lain',
  'Mengendalikan tumbuhan',
  'Mengubah bentuk sesuka hati',
  'Membuat diri tidak terlihat',
  'Membekukan waktu',
  'Teleportasi instan',
  'Menghilang dalam sekejap',
  'Berjalan di atas air',
  'Melompat sejauh 1 kilometer',
  'Menahan napas selama 1 jam',
  'Kekuatan super manusia',
  'Kebal terhadap semua serangan',
  'Melihat masa depan',
  'Berbicara dengan hewan',
  'Terbang bebas di langit',
  'Menembus tembok',
  'Mengeluarkan laser dari mata',
  'Memanggil makhluk gaib',
  'Mengendalikan pasir seperti dewa',
  'Memanipulasi gravitasi',
  'Mengunci ruang dan waktu',
  'Mengatur keberuntungan',
  'Meniru kekuatan musuh',
  'Menyerap kekuatan musuh',
  'Mengubah malam jadi siang',
  'Memanggil makhluk mitos',
  'Membuka portal ke dunia lain',
  'Menyalin teknik siapa pun',
  'Mengendalikan benda kecil dari jauh',
  'Membekukan udara jadi es tajam',
  'Menanamkan ketakutan dalam pikiran',
  'Menghapus jejak keberadaan',
  'Menciptakan realitas alternatif',
  'Mengalihkan serangan ke dimensi lain',
  'Mengendalikan waktu biologis',
  'Mengubah sentuhan jadi emas',
  'Menarik petir dari langit',
  'Mengubah keringat jadi asam',
  'Mengendalikan suhu tubuh ekstrem',
  'Membuat badai di ruang tertutup',
  'Menciptakan ilusi massal',
  'Mengakses semua jaringan data dengan pikiran',
  'Membakar tanpa api',
  'Mengubah napas jadi kabut racun',
  'Mengendalikan elemen api',
  'Menghidupkan benda mati',
  'Mendengar suara dari jarak jauh',
  'Menyembuhkan luka hanya dengan sentuhan',
  'Tidak pernah lelah',
  'Membuat gempa bumi mini',
  'Mengeluarkan aura perlindungan',
  'Mempengaruhi mimpi orang',
  'Berbicara dalam semua bahasa',
  'Melipatgandakan diri',
  'Menghapus ingatan sementara',
  'Kekuatan ilusi tingkat tinggi',
  'Menciptakan api dari udara',
  'Mengeluarkan racun dari tubuh',
  'Membuat hujan deras tiba-tiba',
  'Menciptakan perisai energi',
  'Menggandakan kekuatan lawan untuk diri sendiri',
  'Membaca sejarah benda hanya dengan menyentuhnya',
  'Mengubah air menjadi senjata',
  'Membelah bumi dengan pukulan',
  'Menyerang melalui pantulan',
  'Membekukan waktu dengan sihir peri salju',
  'Menggandakan tubuh dengan kekuatan jin pengganda',
  'Menyeru pasukan undead dari tanah terlarang',
  'Mengendalikan kristal sihir milik bangsa bawah tanah',
  'Menciptakan senjata dari cahaya murni',
  'Mengendalikan hujan darah dari langit neraka',
  'Membaca takdir dengan mata elf waktu',
  'Menjadi bayangan dewa kegelapan',
  'Menyegel kekuatan iblis dalam tubuh sendiri',
  'Memanggil naga kembar pelindung dimensi',
  'Menghapus dosa dengan tangan cahaya peri',
  'Mengendalikan akar suci dari pohon dunia',
  'Menciptakan sihir pelindung keturunan naga putih',
  'Menyerap kekuatan elemen lewat napas naga hitam',
  'Mengikat iblis dengan kalung batu roh',
  'Menjadi penengah antara dunia hidup dan alam roh',
  'Kekuatan naga legendaris',
  'Membangkitkan roh leluhur',
  'Kekuatan serigala malam',
  'Mengendalikan cahaya suci keturunan elf',
  'Membakar jiwa dengan api abadi warisan naga',
  'Memanggil roh penjaga hutan kuno',
  'Mengendalikan waktu dengan sihir elf kuno',
  'Menembus dimensi lewat bayangan iblis',
  'Menciptakan pelindung cahaya dari darah malaikat',
  'Menyerap kekuatan bulan warisan ras lycan',
  'Mengendalikan badai dengan pusaka suku naga langit',
  'Mengubah bisikan jadi mantra kutukan iblis',
  'Mengendalikan petir surgawi dari keturunan titan',
  'Mengutuk musuh dengan tatapan peri malam',
  'Menghidupkan senjata dengan roh leluhur',
  'Memanggil penjaga gerbang neraka',
  'Menghidupkan orang mati dengan sihir terlarang'
];

module.exports = {
  sifatlist,
  when,
  ask,
  cekKhodam,
  cekKuat,
  cekDosa
};