const fs = require("fs");

const sifatlist = [
  'Baik',
  'Jahat',
  'Lucu',
  'Pemarah',
  'Penyabar',
  'Pemalu',
  'Percaya Diri',
  'Pemberani',
  'Cengeng',
  'Bijaksana',
  'Pintar',
  'Sombong',
  'Rendah Hati',
  'Setia',
  'Cemburuan',
  'Pelit',
  'Dermawan',
  'Pemalas',
  'kek kontol',
  'Rajin',
  'Sensitif'
];

const when = [
  'aku benar-benar bahagia',
  'kita ketemu lagi',
  'semuanya jadi lebih mudah',
  'aku bisa membanggakan orang tuaku',
  'aku bisa berhenti capek terus',
  'mimpi jadi kenyataan',
  'aku diseriusin',
  'hidup nggak sesulit ini',
  'aku merasa cukup',
  'rasa ini hilang',
  'ada yang bener-bener sayang sama aku',
  'aku bisa tidur tanpa mikir apa-apa',
  'dompetku tebal bukan karena struk',
  'ada yang ngajak nikah',
  'hidup nggak cuma bangun–kerja–capek–ulang lagi',
  'aku nggak jadi plan B orang',
  'bisa rebahan tanpa rasa bersalah',
  'aku nggak salah terus di mata orang',
  '100 tahun lagi',
  'owner jadi femboy',
  'aku dikira ganteng tanpa harus buka filter',
  'rambut rontok bisa diklaim BPJS'
  ];

const ask = [
  'Ya, dia gay',
  'Mungkin iya',
  'Sebaiknya jangan 🗿',
  'Diem lu',
  'Gay',
  'Aduh le 100% sih',
  'Coba tanya admin',
  'Kau tak di ajak',
  'Betul',
  'Enggak kok',
  'Enggak, dia ganteng malahan',
  'Enggak, dia cantik malahan',
  'Kata siapa?, jelas-jelas kek kontol',
  'Lu yang kek kontol',
  'Coba tebak',
  'Tanya mulu lu',
  'Gak tau gw',
  'Tanya owner',
  'Y',
  'G'
  ];

const cekKhodam = [
  'Kosong',
  'Kucing Rawa',
  'Biawak Samudra',
  'Kipas Angis',
  'Farhan Kebab',
  'Rossi Becak',
  'Karyawan Indomaret',
  'Peti Harta',
  'Kuntilanak Lucu',
  'Pocong berkepala 3',
  'Kapal karam',
  'Pace Yunus',
  'Ciput',
  'Kepala casan',
  'Bando kucing',
  'Pisang Hijau',
  'Pinguin Alaskar',
  'Zebra Merah',
  'Gondoruwo',
  'Ikan Mas',
  'Biawak',
  'Singa',
  'Zebra',
  'Ikan Sepat',
  'Ikan Gabus',
  'Ular Piton',
  'Ular Kobra',
  'Harimau',
  'Macan',
  'Handuk basah',
  'Suster ngesot',
  'Tuyul',
  'Titid kuda',
  'Torpedo kambing',
  'Sapi',
  'Kerbau',
  'Domba',
  'Serigala',
  'Elang',
  'Cacing',
  'Ulat bulu',
  'Pace',
  'Siimut dari jawa',
  'Mama',
  'Papa',
  'Adek',
  'Nenek',
  'Pinokio',
  'Cinderela',
  'Trenggiling',
  'Agus',
  'Rusdi Boti',
  'Listrik Kejut',
  'Naruto',
  'Biawak Sumatera',
  'Semut Hitam',
  'Pinokio',
  'Naga Merah',
  'Barbie',
  'Kapal karam',
  'Siput Sumatra',
  'Serigala berbulu janda',
  'Lemari kecoa',
  'Hiu sumanji',
  'Sempak Firaun',
  'Kaori',
  'Walid',
  'Sapi terbang',
  'Jerapah Pendek',
  'Janda anak Pitu',
  'Kue jeli pak Herman',
  'Serigala Jawa',
  'Singa dangdut',
  'Macan kembang',
  'Macan hideng',
  'Macan Ireng',
  'Nyamuk racing',
  'Minyak resing',
  'Api Hermansyah'
];

module.exports = {
  sifatlist,
  when,
  ask,
  cekKhodam
}